### ISSUE TITLE
Can't install plugin with hyphen in the name

### ISSUE THREAD

**Issue by RobErskine** [wesrice/rest-easy#2]
Not sure when Craft changed their plugin naming conventions, but if a plugin folder has a hyphen (-) in the name, Craft will not pick it up.

Renaming the folder from "rest-east" to "resteasy" fixed this for me.

**Comment by roelvanhintum** [comment]
I'm having the same problem.

**Comment by wesrice** [comment]
@RobErskine @roelvanhintum - Hey guys, I deeply apologize, but this is abandonware and I no longer support this. Please feel free to fork it. I will make this abundantly clear in the readme file soon.
